name: Build and test

on:
  pull_request:
    branches: [main]

jobs:
  call-workflow:
    uses: ./.github/workflows/build_and_publish_template.yml
    permissions:
      contents: read
      id-token: write
    with:
      upload_wheels: false
